---
- name: Shell and CLI tools setup (Zsh, Oh My Zsh, bash_aliases, fzf, zoxide, ugrep, Nerd Font)
  hosts: localhost
  tasks:
    - name: Install zsh (Debian)
      become: yes
      apt:
        name: zsh
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install zsh (Mac)
      homebrew:
        name: zsh
        state: present
      when: ansible_os_family == 'Darwin'
      become: false

    - name: Install git (Debian)
      become: yes
      apt:
        name: git
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install git (Mac)
      homebrew:
        name: git
        state: present
      when: ansible_os_family == 'Darwin'
      become: false

    - name: Install Oh My Zsh
      become: false
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh

    - name: Symlink custom zshrc
      file:
        src: ~/Privat/useful_scripts/shell_setup/omzsh/zshrc
        dest: ~/.zshrc
        state: link
        force: yes

    - name: Symlink custom bash_aliases
      file:
        src: ~/Privat/useful_scripts/shell_setup/bash_aliases
        dest: ~/.bash_aliases
        state: link
        force: yes

    - name: Set zsh as default shell (Debian)
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      when: ansible_os_family == 'Debian'

    - name: Set zsh as default shell (Mac)
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      when: ansible_os_family == 'Darwin'

    - name: Install fzf (latest from repo)
      become: false
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install --all
      args:
        creates: ~/.fzf

    - name: Install zoxide (Debian)
      become: yes
      apt:
        name: zoxide
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install zoxide (macOS)
      homebrew:
        name: zoxide
        state: present
      when: ansible_os_family == 'Darwin'
      become: false

    - name: Install ugrep (Debian)
      become: yes
      apt:
        name: ugrep
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install ugrep (macOS)
      homebrew:
        name: ugrep
        state: present
      when: ansible_os_family == 'Darwin'
      become: false

    - name: Install Powerlevel10k theme for Oh My Zsh
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        update: yes

    - name: Ensure p10k.zsh config is symlinked
      file:
        src: ~/Privat/useful_scripts/shell_setup/omzsh/p10k.zsh
        dest: ~/.p10k.zsh
        state: link
        force: yes

    - name: Install Nerd Fonts (JetBrainsMono)
      become: yes
      shell: |
        mkdir -p ~/.local/share/fonts
        wget -O /tmp/JetBrainsMono.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        unzip -o /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/
        fc-cache -fv
      when: ansible_os_family == 'Debian'
      args:
        creates: ~/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf

    - name: Install Nerd Fonts (JetBrainsMono) on macOS
      shell: |
        brew install --cask font-jetbrains-mono-nerd-font
      when: ansible_os_family == 'Darwin'
      become: false
