# VIM 
alias vi=nvim
alias init-lua='vi ~/.config/nvim/init.lua'

# GIT
alias gs='git status'
alias ga='git add .'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative -n8"
alias gll="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gcl='git config --list'
alias glc='git log --format="%B"'
alias gc='git checkout'

gitRmBranchesNotOnRemote() {
    git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
}

alias rmVimSwp='rm -r ~/.local/state/nvim/swap/*'

alias ls='ls -F'
alias ll='ls -lha'
alias la='ls -a'

alias zshrc='vi ~/.zshrc && source ~/.zshrc'
alias bashrc='vi ~/.bashrc && source ~/.bashrc'
alias bash_aliases='vi ~/.bash_aliases && source ~/.bash_aliases'

# Display file size and sort by it
alias lt='du -sh * | sort -h'

# Use ugrep instead of grep - uncomment if you have ugrep installed
# alias grep=ugrep

alias xcc='xclip -select clipboard'

# LANGUAGE SPECIFIC
# .NET
alias rmBinObj='find . -iname bin -o -iname obj | xargs rm -rf'
alias csi=csharprepl
