#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (
        find ~/Notes -type d;
        find ~/.config/nvim -maxdepth 0 -type d; 
        find ~/.scripts -maxdepth 0 -type d; # single folder (without it's children) you want to add to the list
        find ~/Work/ ~/Privat/ ~/Desktop/ -mindepth 1 -maxdepth 2 -type d) | fzf --tmux=80%,80%)
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo $selected
