#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (
        find ~/notes -type d;
        find ~/.config/nvim -maxdepth 0 -type d;
        find ~/.scripts -maxdepth 0 -type d; # single folder (without it's children) you want to add to the list
        find ~/Work/Learning ~/Work/TowerManagement/ ~/Privat/ ~/Desktop/ -mindepth 1 -maxdepth 1 -type d) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi


tmux switch-client -t $selected_name
